local o = vim.o
local g = vim.g
local api = vim.api

vim.cmd("hi clear")

if g.syntax_on == 1 then
	vim.cmd("syntax reset")
end

o.background = "dark"
g.colors_name = "feuerblatt"

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#939E9F", bg = "#1D2520"},
ALEError = {fg = "#c4331d", bold = true},
ALEErrorSign = {fg = "#c4331d", bold = true},
ALEWarning = {fg = "#b37f02", bold = true},
ALEWarningSign = {fg = "#b37f02", bold = true},
BlackOnLightYellow = {fg = "#939E9F", bg = "#f9eab3"},
Bold = {fg = "#939E9F", bold = true},
ColorColumn = {bg = "#eeeeee"},
Comment = {fg = "#5B5F4E"},
EyelinerDimmed = {link = "Comment"},
FoldColumn = {link = "Comment"},
Folded = {link = "Comment"},
MiniPickBorderText = {link = "Comment"},
hamlDocType = {link = "Comment"},
markdownCodeBlock = {link = "Comment"},
rustCommentBlockDoc = {link = "Comment"},
rustCommentLineDoc = {link = "Comment"},
Conceal = {},
Constant = {fg = "#939E9F"},
Type = {link = "Constant"},
Cursor = {bg = "#939E9F"},
CursorLine = {bg = "#191F1B"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#63746E", italic = true},
DiagnosticDeprecated = {},
DiagnosticError = {fg = "#c4331d", bold = true},
DiagnosticFloatingError = {fg = "#c4331d", bold = true},
DiagnosticFloatingHint = {fg = "#939E9F", bold = true},
DiagnosticFloatingInfo = {fg = "#1561b8", bold = true},
DiagnosticFloatingWarn = {fg = "#b37f02", bold = true},
DiagnosticHint = {fg = "#5e5e5e", bold = true},
DiagnosticInfo = {fg = "#1561b8", bold = true},
DiagnosticUnderlineError = {sp = "#c4331d", underline = true},
LspDiagnosticsUnderlineError = {link = "DiagnosticUnderlineError"},
DiagnosticUnderlineWarn = {sp = "#b37f02", underline = true},
LspDiagnosticsUnderlineWarning = {link = "DiagnosticUnderlineWarn"},
DiagnosticWarn = {fg = "#b37f02", bold = true},
DiffAdd = {bg = "#dfeacc"},
diffAdded = {link = "DiffAdd"},
DiffChange = {bg = "#eeeeee"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#c4331d"},
diffRemoved = {link = "DiffDelete"},
DiffText = {bg = "#f9eab3"},
DiffviewCursorLine = {bg = "#000000", bold = true},
DiffviewDiffAddAsDelete = {bg = "#f2d3cd"},
DiffviewDiffDelete = {fg = "#000000"},
DiffviewDiffDeleteDim = {fg = "#000000"},
DiffviewFilePanelDeletions = {fg = "#c4331d"},
DiffviewFilePanelFileName = {fg = "#939E9F"},
DiffviewFilePanelInsertions = {fg = "#1C5708"},
DiffviewFilePanelPath = {fg = "#5c21a5"},
DiffviewFilePanelRootPath = {fg = "#5c21a5"},
DiffviewFilePanelTitle = {fg = "#939E9F", bold = true},
DiffviewStatusAdded = {fg = "#1C5708", bold = true},
DiffviewStatusCopied = {fg = "#1C5708", bold = true},
DiffviewStatusDeleted = {fg = "#c4331d", bold = true},
DiffviewStatusModified = {fg = "#b37f02", bold = true},
Directory = {fg = "#5c21a5"},
htmlLink = {link = "Directory"},
javaAnnotation = {link = "Directory"},
Disabled = {},
EndOfBuffer = {fg = "#1D2520", bg = "#1D2520"},
ErrorMsg = {fg = "#FF0000"},
Error = {link = "ErrorMsg"},
gitCommitOverflow = {link = "ErrorMsg"},
EyelinerPrimary = {fg = "#c4331d", bold = true},
EyelinerSecondary = {fg = "#b37f02", bold = true},
FlashLabel = {fg = "#939E9F", bg = "#f9db70", bold = true},
FlashPromptIcon = {bold = true},
FloatBorder = {fg = "#cccccc"},
CccFloatBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#939E9F", bold = true},
SignColumn = {link = "FoldColumn"},
FugitiveblameHash = {fg = "#5c21a5"},
FugitiveblameTime = {fg = "#1561b8"},
Function = {fg = "#457863"},
makeTarget = {link = "Function"},
typescriptFunction = {link = "Function"},
GitSignsAdd = {fg = "#cccccc"},
GitSignsChange = {fg = "#cccccc"},
GitSignsDelete = {fg = "#cccccc"},
GitSignsStagedAdd = {fg = "#5e5e5e"},
GitSignsStagedChange = {fg = "#5e5e5e"},
GitSignsStagedDelete = {fg = "#5e5e5e"},
HopNextKey = {fg = "#939E9F", bg = "#f9db70", bold = true},
HopNextKey1 = {bg = "#f9eab3"},
HopNextKey2 = {bg = "#f9eab3"},
HopUnmatched = {},
Identifier = {fg = "#939E9F"},
cssProp = {link = "Identifier"},
htmlArg = {link = "Identifier"},
javaScriptMember = {link = "Identifier"},
rustFuncCall = {link = "Identifier"},
rustModPath = {link = "Identifier"},
typescriptIdentifier = {link = "Identifier"},
["@attribute.rust"] = {link = "Identifier"},
IncSearch = {fg = "#030302", bg = "#C48945"},
Include = {fg = "#939E9F", bold = true},
inkoInstanceVariable = {link = "InstanceVariable"},
["@variable.member.inko"] = {link = "InstanceVariable"},
Keyword = {fg = "#9FAC91"},
Boolean = {link = "Keyword"},
Label = {link = "Keyword"},
Statement = {link = "Keyword"},
StorageClass = {link = "Keyword"},
cssClassName = {link = "Keyword"},
cssIdentifier = {link = "Keyword"},
cssImportant = {link = "Keyword"},
cssTagName = {link = "Keyword"},
javaExternal = {link = "Keyword"},
javaScriptFunction = {link = "Keyword"},
javaScriptIdentifier = {link = "Keyword"},
javaStorageClass = {link = "Keyword"},
luaFunction = {link = "Keyword"},
markdownListMarker = {link = "Keyword"},
markdownOrderedListMarker = {link = "Keyword"},
pythonOperator = {link = "Keyword"},
shFunctionKey = {link = "Keyword"},
sqlKeyword = {link = "Keyword"},
typescriptExceptions = {link = "Keyword"},
typescriptFuncKeyword = {link = "Keyword"},
["@constant.builtin.inko"] = {link = "Keyword"},
LightRedBackground = {bg = "#f2d3cd"},
LineNr = {fg = "#5B5F4E", italic = true},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspReferenceTarget = {},
Macro = {fg = "#a55000"},
PreCondit = {link = "Macro"},
["@function.macro.rust"] = {link = "Macro"},
MatchParen = {bold = true},
MiniDiffSignAdd = {fg = "#cccccc"},
MiniDiffSignChange = {fg = "#cccccc"},
MiniDiffSignDelete = {fg = "#cccccc"},
MiniIconsAzure = {fg = "#1561b8"},
MiniIconsBlue = {fg = "#1561b8"},
MiniIconsCyan = {fg = "#007872"},
MiniIconsGreen = {fg = "#1C5708"},
MiniIconsGrey = {fg = "#5e5e5e"},
MiniIconsOrange = {fg = "#a55000"},
MiniIconsPurple = {fg = "#5c21a5"},
MiniIconsRed = {fg = "#c4331d"},
MiniIconsYellow = {fg = "#b37f02"},
MiniJump2dSpot = {fg = "#c4331d", bold = true},
MiniJump2dSpotAhead = {fg = "#c4331d", bold = true},
MiniPickBorder = {fg = "#cccccc"},
MiniPickBorderBusy = {link = "MiniPickBorder"},
MiniPickHeader = {fg = "#939E9F", bold = true},
MiniPickMatchCurrent = {bg = "#000000", bold = true},
MiniPickMatchMarked = {bold = true},
MiniPickMatchRanges = {fg = "#b37f02", bold = true},
MiniPickNormal = {fg = "#939E9F"},
MiniPickPrompt = {fg = "#939E9F"},
MiniStatuslineModeCommand = {fg = "#939E9F", bg = "#242E27"},
MiniStatuslineModeNormal = {fg = "#939E9F", bg = "#242E27"},
ModeMsg = {fg = "#939E9F", bold = true},
MoreMsg = {fg = "#939E9F"},
MsgSeparator = {fg = "#cccccc"},
NonText = {fg = "#5e5e5e"},
FlashBackdrop = {link = "None"},
PounceGap = {link = "None"},
NormalFloat = {fg = "#939E9F"},
CccFloatNormal = {link = "NormalFloat"},
JavaScriptNumber = {link = "Number"},
SpecialKey = {link = "Number"},
cssColor = {link = "Number"},
inkoCommentInlineUrl = {link = "Number"},
OkMsg = {fg = "#009963"},
Operator = {fg = "#939E9F"},
dotKeyChar = {link = "Operator"},
javaScriptBraces = {link = "Operator"},
typescriptBraces = {link = "Operator"},
typescriptEndColons = {link = "Operator"},
typescriptLogicSymbols = {link = "Operator"},
Pmenu = {fg = "#939E9F", bg = "#1D2520"},
PmenuMatch = {fg = "#b37f02", bold = true},
PmenuSbar = {bg = "#1D2520"},
PmenuSel = {bg = "#000000", bold = true},
WildMenu = {link = "PmenuSel"},
PmenuThumb = {bg = "#000000"},
PounceAccept = {fg = "#939E9F", bg = "#f9db70", bold = true},
PounceAcceptBest = {link = "PounceAccept"},
PounceMatch = {bg = "#f9eab3"},
PounceUnmatched = {},
PreProc = {fg = "#939E9F"},
Question = {fg = "#939E9F"},
QuickFixLine = {bg = "#eeeeee", bold = true},
Regexp = {fg = "#a55000"},
inkoKeywordArgument = {link = "Regexp"},
["@string.regexp"] = {link = "Regexp"},
CurSearch = {link = "Search"},
SnippetTabstop = {},
SnippyPlaceholder = {link = "SnippetTabstop"},
Special = {fg = "#939E9F"},
SpellBad = {sp = "#c4331d", underline = true},
SpellCap = {sp = "#b37f02", underline = true},
SpellLocal = {sp = "#1561b8", underline = true},
SpellRare = {sp = "#5c21a5", underline = true},
StatusLine = {fg = "#939E9F", bg = "#1D2520"},
StatusLineNC = {fg = "#939E9F", bg = "#1D2520"},
StatusLineTab = {fg = "#939E9F", bg = "#1D2520", bold = true},
String = {fg = "#78977B"},
Character = {link = "String"},
gitCommitSummary = {link = "String"},
jsonKeyword = {link = "String"},
Symbol = {fg = "#a55000"},
TabLine = {fg = "#939E9F", bg = "#000000"},
TabLineFill = {fg = "#939E9F", bg = "#000000"},
TabLineSel = {fg = "#939E9F", bg = "#1D2520", bold = true},
TelescopeBorder = {fg = "#cccccc"},
TelescopeMatching = {fg = "#b37f02", bold = true},
TelescopeNormal = {fg = "#939E9F"},
TelescopePromptBorder = {fg = "#cccccc"},
TelescopePromptNormal = {fg = "#939E9F"},
TelescopePromptPrefix = {fg = "#939E9F", bold = true},
TelescopeSelection = {fg = "#8B9C95", bg = "#78977B", bold = true},
TelescopeTitle = {fg = "#939E9F", bold = true},
Title = {fg = "#939E9F", bold = true},
Todo = {fg = "#5e5e5e", bold = true},
javaDocParam = {link = "Todo"},
javaDocTags = {link = "Todo"},
Underlined = {underline = true},
VertSplit = {fg = "#cccccc"},
Visual = {fg = "#1D2520", bg = "#939E9F"},
WarningMsg = {fg = "#9B5A22"},
WhiteOnBlue = {fg = "#ffffff", bg = "#1561b8"},
WhiteOnOrange = {fg = "#ffffff", bg = "#a55000"},
WhiteOnRed = {fg = "#ffffff", bg = "#c4331d"},
WhiteOnYellow = {fg = "#ffffff", bg = "#b37f02"},
Whitespace = {fg = "#cccccc"},
WinBar = {fg = "#1D2520", bold = true},
WinBarFill = {fg = "#cccccc"},
WinBarNc = {fg = "#1D2520", bold = true},
WinSeparator = {fg = "#cccccc"},
Yellow = {fg = "#b37f02", bold = true},
sassClass = {link = "cssClassName"},
["@type.css"] = {link = "cssClassName"},
cssCustomProp = {fg = "#5c21a5"},
["@variable.css"] = {link = "cssCustomProp"},
sassId = {link = "cssIdentifier"},
["@tag.css"] = {link = "cssIdentifier"},
cssPseudoClass = {fg = "#a55000", bold = true},
cssPseudoClassId = {link = "cssPseudoClass"},
["@constant.css"] = {link = "cssTagName"},
diffFile = {fg = "#939E9F", bold = true},
diffLine = {fg = "#1561b8"},
hamlClass = {fg = "#939E9F"},
hamlId = {fg = "#939E9F"},
hamlTag = {fg = "#939E9F", bold = true},
htmlBold = {bold = true},
htmlItalic = {italic = true},
htmlTag = {fg = "#939E9F", bold = true},
htmlScriptTag = {link = "htmlTag"},
htmlSpecialTagName = {link = "htmlTag"},
htmlTagName = {link = "htmlTag"},
inkoCommentBold = {fg = "#5e5e5e", bold = true},
inkoCommentItalic = {fg = "#5e5e5e", italic = true},
inkoCommentTitle = {fg = "#5e5e5e", bold = true},
javaCommentTitle = {link = "javaComment"},
markdownCode = {link = "markdownCodeBlock"},
markdownUrl = {fg = "#1561b8"},
["search_base"] = {fg = "#1C1B17", bg = "#C4B345"},
Search = {link = "search_base"},
["@comment.warning.gitcommit"] = {fg = "#c4331d", bold = true},
["@markup.link"] = {fg = "#1561b8"},
["@markup.link.gitcommit"] = {fg = "#1C5708", bold = true},
["@property.json"] = {bold = true},
["@punctuation"] = {fg = "#939E9F"},
["@string.special.url.gitcommit"] = {fg = "#939E9F"},
["@text.emphasis"] = {italic = true},
["@text.reference"] = {fg = "#5c21a5"},
["@text.strong"] = {bold = true},
["@text.uri"] = {fg = "#1561b8"},
["@variable"] = {fg = "#939E9F"},
["@variable.builtin"] = {bold = true},
["@variable.parameter.reference"] = {fg = "#a55000"},
	-- PATCH_CLOSE
	-- content here will not be touched
}

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
