local o = vim.o
local g = vim.g
local api = vim.api

vim.cmd("hi clear")

if g.syntax_on == 1 then
	vim.cmd("syntax reset")
end

o.background = "dark"
g.colors_name = "orangen"

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
	Normal = { fg = "#FA8C47", bg = "#000000" },
	ALEError = { fg = "#c4331d", bold = true },
	ALEErrorSign = { fg = "#c4331d", bold = true },
	ALEWarning = { fg = "#b37f02", bold = true },
	ALEWarningSign = { fg = "#b37f02", bold = true },
	BlackOnLightYellow = { fg = "#FA8C47", bg = "#f9eab3" },
	Bold = { fg = "#FA8C47", bold = true },
	ColorColumn = { bg = "#eeeeee" },
	Comment = { fg = "#699060" },
	EyelinerDimmed = { link = "Comment" },
	FoldColumn = { link = "Comment" },
	Folded = { link = "Comment" },
	MiniPickBorderText = { link = "Comment" },
	hamlDocType = { link = "Comment" },
	markdownCodeBlock = { link = "Comment" },
	rustCommentBlockDoc = { link = "Comment" },
	rustCommentLineDoc = { link = "Comment" },
	Conceal = {},
	Constant = { fg = "#FA8C47" },
	Type = { link = "Constant" },
	Cursor = { bg = "#FA8C47" },
	CursorLine = { bg = "#004C4D" },
	CursorColumn = { link = "CursorLine" },
	CursorLineNr = { fg = "#9A8E51", italic = true },
	DiagnosticDeprecated = {},
	DiagnosticError = { fg = "#c4331d", bold = true },
	DiagnosticFloatingError = { fg = "#c4331d", bold = true },
	DiagnosticFloatingHint = { fg = "#FA8C47", bold = true },
	DiagnosticFloatingInfo = { fg = "#1561b8", bold = true },
	DiagnosticFloatingWarn = { fg = "#b37f02", bold = true },
	DiagnosticHint = { fg = "#5e5e5e", bold = true },
	DiagnosticInfo = { fg = "#1561b8", bold = true },
	DiagnosticUnderlineError = { sp = "#c4331d", underline = true },
	LspDiagnosticsUnderlineError = { link = "DiagnosticUnderlineError" },
	DiagnosticUnderlineWarn = { sp = "#b37f02", underline = true },
	LspDiagnosticsUnderlineWarning = { link = "DiagnosticUnderlineWarn" },
	DiagnosticWarn = { fg = "#b37f02", bold = true },
	DiffAdd = { bg = "#dfeacc" },
	diffAdded = { link = "DiffAdd" },
	DiffChange = { bg = "#eeeeee" },
	diffChanged = { link = "DiffChange" },
	DiffDelete = { fg = "#c4331d" },
	diffRemoved = { link = "DiffDelete" },
	DiffText = { bg = "#f9eab3" },
	DiffviewCursorLine = { bg = "#000000", bold = true },
	DiffviewDiffAddAsDelete = { bg = "#f2d3cd" },
	DiffviewDiffDelete = { fg = "#000000" },
	DiffviewDiffDeleteDim = { fg = "#000000" },
	DiffviewFilePanelDeletions = { fg = "#c4331d" },
	DiffviewFilePanelFileName = { fg = "#FA8C47" },
	DiffviewFilePanelInsertions = { fg = "#1C5708" },
	DiffviewFilePanelPath = { fg = "#D4BD8C" },
	DiffviewFilePanelRootPath = { fg = "#D4BD8C" },
	DiffviewFilePanelTitle = { fg = "#FA8C47", bold = true },
	DiffviewStatusAdded = { fg = "#1C5708", bold = true },
	DiffviewStatusCopied = { fg = "#1C5708", bold = true },
	DiffviewStatusDeleted = { fg = "#c4331d", bold = true },
	DiffviewStatusModified = { fg = "#b37f02", bold = true },
	Directory = { fg = "#D4BD8C" },
	htmlLink = { link = "Directory" },
	javaAnnotation = { link = "Directory" },
	Disabled = {},
	EndOfBuffer = { fg = "#000000", bg = "#000000" },
	ErrorMsg = { fg = "#FF0000" },
	Error = { link = "ErrorMsg" },
	gitCommitOverflow = { link = "ErrorMsg" },
	EyelinerPrimary = { fg = "#c4331d", bold = true },
	EyelinerSecondary = { fg = "#b37f02", bold = true },
	FlashLabel = { fg = "#FA8C47", bg = "#f9db70", bold = true },
	FlashPromptIcon = { bold = true },
	FloatBorder = { fg = "#cccccc" },
	CccFloatBorder = { link = "FloatBorder" },
	FloatTitle = { fg = "#FA8C47", bold = true },
	SignColumn = { link = "FoldColumn" },
	FugitiveblameHash = { fg = "#D4BD8C" },
	FugitiveblameTime = { fg = "#1561b8" },
	Function = { fg = "#FA8C47" },
	makeTarget = { link = "Function" },
	typescriptFunction = { link = "Function" },
	GitSignsAdd = { fg = "#cccccc" },
	GitSignsChange = { fg = "#cccccc" },
	GitSignsDelete = { fg = "#cccccc" },
	GitSignsStagedAdd = { fg = "#5e5e5e" },
	GitSignsStagedChange = { fg = "#5e5e5e" },
	GitSignsStagedDelete = { fg = "#5e5e5e" },
	HopNextKey = { fg = "#FA8C47", bg = "#f9db70", bold = true },
	HopNextKey1 = { bg = "#f9eab3" },
	HopNextKey2 = { bg = "#f9eab3" },
	HopUnmatched = {},
	Identifier = { fg = "#FA8C47" },
	cssProp = { link = "Identifier" },
	htmlArg = { link = "Identifier" },
	javaScriptMember = { link = "Identifier" },
	rustFuncCall = { link = "Identifier" },
	rustModPath = { link = "Identifier" },
	typescriptIdentifier = { link = "Identifier" },
	["@attribute.rust"] = { link = "Identifier" },
	IncSearch = { fg = "#030302", bg = "#C48945" },
	Include = { fg = "#FA8C47", bold = true },
	inkoInstanceVariable = { link = "InstanceVariable" },
	["@variable.member.inko"] = { link = "InstanceVariable" },
	Boolean = { link = "Keyword" },
	Label = { link = "Keyword" },
	Statement = { link = "Keyword" },
	StorageClass = { link = "Keyword" },
	cssClassName = { link = "Keyword" },
	cssIdentifier = { link = "Keyword" },
	cssImportant = { link = "Keyword" },
	cssTagName = { link = "Keyword" },
	javaExternal = { link = "Keyword" },
	javaScriptFunction = { link = "Keyword" },
	javaScriptIdentifier = { link = "Keyword" },
	javaStorageClass = { link = "Keyword" },
	luaFunction = { link = "Keyword" },
	markdownListMarker = { link = "Keyword" },
	markdownOrderedListMarker = { link = "Keyword" },
	pythonOperator = { link = "Keyword" },
	shFunctionKey = { link = "Keyword" },
	sqlKeyword = { link = "Keyword" },
	typescriptExceptions = { link = "Keyword" },
	typescriptFuncKeyword = { link = "Keyword" },
	["@constant.builtin.inko"] = { link = "Keyword" },
	LightRedBackground = { bg = "#f2d3cd" },
	LineNr = { fg = "#699060", italic = true },
	LineNrAbove = { link = "LineNr" },
	LineNrBelow = { link = "LineNr" },
	LspReferenceTarget = {},
	Macro = { fg = "#a55000" },
	PreCondit = { link = "Macro" },
	["@function.macro.rust"] = { link = "Macro" },
	MatchParen = { bold = true },
	MiniDiffSignAdd = { fg = "#cccccc" },
	MiniDiffSignChange = { fg = "#cccccc" },
	MiniDiffSignDelete = { fg = "#cccccc" },
	MiniIconsAzure = { fg = "#1561b8" },
	MiniIconsBlue = { fg = "#1561b8" },
	MiniIconsCyan = { fg = "#007872" },
	MiniIconsGreen = { fg = "#1C5708" },
	MiniIconsGrey = { fg = "#5e5e5e" },
	MiniIconsOrange = { fg = "#a55000" },
	MiniIconsPurple = { fg = "#D4BD8C" },
	MiniIconsRed = { fg = "#c4331d" },
	MiniIconsYellow = { fg = "#b37f02" },
	MiniJump2dSpot = { fg = "#c4331d", bold = true },
	MiniJump2dSpotAhead = { fg = "#c4331d", bold = true },
	MiniPickBorder = { fg = "#cccccc" },
	MiniPickBorderBusy = { link = "MiniPickBorder" },
	MiniPickHeader = { fg = "#FA8C47", bold = true },
	MiniPickMatchCurrent = { bg = "#000000", bold = true },
	MiniPickMatchMarked = { bold = true },
	MiniPickMatchRanges = { fg = "#b37f02", bold = true },
	MiniPickNormal = { fg = "#FA8C47" },
	MiniPickPrompt = { fg = "#FA8C47" },
	MiniStatuslineModeCommand = { fg = "#FA8C47", bg = "#007070" },
	MiniStatuslineModeNormal = { fg = "#FA8C47", bg = "#007070" },
	ModeMsg = { fg = "#FA8C47", bold = true },
	MoreMsg = { fg = "#FA8C47" },
	MsgSeparator = { fg = "#cccccc" },
	NonText = { fg = "#5e5e5e" },
	FlashBackdrop = { link = "None" },
	PounceGap = { link = "None" },
	NormalFloat = { fg = "#FA8C47" },
	CccFloatNormal = { link = "NormalFloat" },
	JavaScriptNumber = { link = "Number" },
	SpecialKey = { link = "Number" },
	cssColor = { link = "Number" },
	inkoCommentInlineUrl = { link = "Number" },
	OkMsg = { fg = "#009963" },
	Operator = { fg = "#FA8C47" },
	dotKeyChar = { link = "Operator" },
	javaScriptBraces = { link = "Operator" },
	typescriptBraces = { link = "Operator" },
	typescriptEndColons = { link = "Operator" },
	typescriptLogicSymbols = { link = "Operator" },
	Pmenu = { fg = "#FA8C47", bg = "#000000" },
	PmenuMatch = { fg = "#b37f02", bold = true },
	PmenuSbar = { bg = "#000000" },
	PmenuSel = { bg = "#000000", bold = true },
	WildMenu = { link = "PmenuSel" },
	PmenuThumb = { bg = "#000000" },
	PounceAccept = { fg = "#FA8C47", bg = "#f9db70", bold = true },
	PounceAcceptBest = { link = "PounceAccept" },
	PounceMatch = { bg = "#f9eab3" },
	PounceUnmatched = {},
	PreProc = { fg = "#FA8C47" },
	Question = { fg = "#FA8C47" },
	QuickFixLine = { bg = "#eeeeee", bold = true },
	Regexp = { fg = "#a55000" },
	inkoKeywordArgument = { link = "Regexp" },
	["@string.regexp"] = { link = "Regexp" },
	CurSearch = { link = "Search" },
	SnippetTabstop = {},
	SnippyPlaceholder = { link = "SnippetTabstop" },
	Special = { fg = "#FA8C47" },
	SpellBad = { sp = "#c4331d", underline = true },
	SpellCap = { sp = "#b37f02", underline = true },
	SpellLocal = { sp = "#1561b8", underline = true },
	SpellRare = { sp = "#D4BD8C", underline = true },
	StatusLine = { fg = "#FA8C47", bg = "#000000" },
	StatusLineNC = { fg = "#FA8C47", bg = "#000000" },
	StatusLineTab = { fg = "#FA8C47", bg = "#000000", bold = true },
	String = { fg = "#FCAB79" },
	Character = { link = "String" },
	gitCommitSummary = { link = "String" },
	jsonKeyword = { link = "String" },
	Symbol = { fg = "#a55000" },
	TabLine = { fg = "#FA8C47", bg = "#000000" },
	TabLineFill = { fg = "#FA8C47", bg = "#000000" },
	TabLineSel = { fg = "#FA8C47", bg = "#000000", bold = true },
	TelescopeBorder = { fg = "#cccccc" },
	TelescopeMatching = { fg = "#b37f02", bold = true },
	TelescopeNormal = { fg = "#FA8C47" },
	TelescopePromptBorder = { fg = "#cccccc" },
	TelescopePromptNormal = { fg = "#FA8C47" },
	TelescopePromptPrefix = { fg = "#FA8C47", bold = true },
	TelescopeSelection = { fg = "#000000", bg = "#ffffff", bold = true },
	TelescopeTitle = { fg = "#FA8C47", bold = true },
	Title = { fg = "#FA8C47", bold = true },
	Todo = { fg = "#5e5e5e", bold = true },
	javaDocParam = { link = "Todo" },
	javaDocTags = { link = "Todo" },
	Underlined = { underline = true },
	VertSplit = { fg = "#cccccc" },
	Visual = { fg = "#000000", bg = "#FA8C47" },
	WarningMsg = { fg = "#9B5A22" },
	WhiteOnBlue = { fg = "#ffffff", bg = "#1561b8" },
	WhiteOnOrange = { fg = "#ffffff", bg = "#a55000" },
	WhiteOnRed = { fg = "#ffffff", bg = "#c4331d" },
	WhiteOnYellow = { fg = "#ffffff", bg = "#b37f02" },
	Whitespace = { fg = "#cccccc" },
	WinBar = { fg = "#000000", bold = true },
	WinBarFill = { fg = "#cccccc" },
	WinBarNc = { fg = "#000000", bold = true },
	WinSeparator = { fg = "#cccccc" },
	Yellow = { fg = "#b37f02", bold = true },
	sassClass = { link = "cssClassName" },
	["@type.css"] = { link = "cssClassName" },
	cssCustomProp = { fg = "#D4BD8C" },
	["@variable.css"] = { link = "cssCustomProp" },
	sassId = { link = "cssIdentifier" },
	["@tag.css"] = { link = "cssIdentifier" },
	cssPseudoClass = { fg = "#a55000", bold = true },
	cssPseudoClassId = { link = "cssPseudoClass" },
	["@constant.css"] = { link = "cssTagName" },
	diffFile = { fg = "#FA8C47", bold = true },
	diffLine = { fg = "#1561b8" },
	hamlClass = { fg = "#FA8C47" },
	hamlId = { fg = "#FA8C47" },
	hamlTag = { fg = "#FA8C47", bold = true },
	htmlBold = { bold = true },
	htmlItalic = { italic = true },
	htmlTag = { fg = "#FA8C47", bold = true },
	htmlScriptTag = { link = "htmlTag" },
	htmlSpecialTagName = { link = "htmlTag" },
	htmlTagName = { link = "htmlTag" },
	inkoCommentBold = { fg = "#5e5e5e", bold = true },
	inkoCommentItalic = { fg = "#5e5e5e", italic = true },
	inkoCommentTitle = { fg = "#5e5e5e", bold = true },
	javaCommentTitle = { link = "javaComment" },
	markdownCode = { link = "markdownCodeBlock" },
	markdownUrl = { fg = "#1561b8" },
	["search_base"] = { fg = "#1C1B17", bg = "#C4B345" },
	Search = { link = "search_base" },
	["@comment.warning.gitcommit"] = { fg = "#c4331d", bold = true },
	["@constant"] = { fg = "#f9db70", bold = true },
	["@function.call"] = { fg = "#FA8C47" },
	["@keyword"] = { fg = "#FCBA92", bold = true },
	["@markup.link"] = { fg = "#1561b8" },
	["@markup.link.gitcommit"] = { fg = "#1C5708", bold = true },
	["@operator"] = { fg = "#FA8C47", bold = true },
	["@property.json"] = { bold = true },
	["@punctuation"] = { fg = "#FA8C47" },
	["@string.special.url.gitcommit"] = { fg = "#FA8C47" },
	["@text.emphasis"] = { italic = true },
	["@text.reference"] = { fg = "#D4BD8C" },
	["@text.strong"] = { bold = true },
	["@text.uri"] = { fg = "#1561b8" },
	["@type"] = { fg = "#FA8C47", bold = true },
	["@type.builtin"] = { fg = "#89AB82" },
	["@variable"] = { fg = "#FA8C47" },
	["@variable.builtin"] = { bold = true },
	["@variable.parameter.reference"] = { fg = "#a55000" },
	-- PATCH_CLOSE
	-- content here will not be touched
}

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
